name: Android Build

on:
  push:
    branches:
      - Build
  pull_request:
    branches:
      - Build

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build project ✨
    runs-on: ubuntu-24.04
    steps:
      # Begin pulling Unity Docker image
      - name: Pull Unity Docker image in background
        run: |
          docker pull unityci/editor:ubuntu-6000.3.10f1-android-3 &

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      # Ensure Library Directory Exists
      - name: Ensure Library directory exists
        run: mkdir -p Library
        
      # Cache
      - uses: actions/cache@v5
        with:
          path: Library
          key: Library-Temp-Linux-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Temp-Linux-${{ runner.os }}-
            Library-Temp-Linux-
            Library-Temp-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: 6000.3.10f1
          customImage: unityci/editor:ubuntu-6000.3.10f1-android-3
          runAsHostUser: true
          versioning: Semantic

      # Ensure Directory Exists
      - name: Ensure build directory exists
        run: mkdir -p build/Android

      # Output
      - uses: actions/upload-artifact@v7
        with:
          name: Build
          path: build/Android